version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: employee_postgres
    environment:
      POSTGRES_DB: employees_db
      POSTGRES_USER: harinee
      POSTGRES_PASSWORD: "Kowshik12$$"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  employee-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee_service
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/employees_db
      SPRING_DATASOURCE_USERNAME: harinee
      SPRING_DATASOURCE_PASSWORD: "Kowshik12$$"
      ADMIN_TOKEN: secret
    restart: on-failure

volumes:
  postgres-data:
